// =============================================================================
// Root layout — applied to every page.
//
// Sets up metadata for SEO + social previews, Inter font, and the shared
// chrome (Nav + Footer) so every page renders identically below the fold.
// =============================================================================

import type { Metadata, Viewport } from 'next';
import { Archivo_Black } from 'next/font/google';
import './globals.css';
import { Nav } from '@/components/Nav';
import { Footer } from '@/components/Footer';
import { Splash } from '@/components/Splash';

// Display face for the brand wordmark only (Nav / Footer / splash). The rest of
// the site stays Inter — this is exposed as a CSS variable so it's opt-in per
// element, not a site-wide type swap.
const archivoBlack = Archivo_Black({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-archivo-black',
  display: 'swap',
});

const TITLE = 'Movvy — Your Move, Booked in 60 Seconds';
const DESCRIPTION =
  "Alberta's moving marketplace. Vetted crews, honest hourly pricing, live tracking " +
  'from pickup to drop-off. Calgary, Edmonton, Red Deer, and beyond.';

export const metadata: Metadata = {
  metadataBase: new URL('https://movvy.ca'),
  title: {
    default: TITLE,
    template: '%s · Movvy',
  },
  description: DESCRIPTION,
  applicationName: 'Movvy',
  keywords: [
    'moving Calgary',
    'movers Calgary',
    'moving Edmonton',
    'Alberta moving company',
    'moving app',
    'book movers',
  ],
  authors: [{ name: 'Movvy Technologies Inc.' }],
  openGraph: {
    type: 'website',
    locale: 'en_CA',
    url: 'https://movvy.ca',
    siteName: 'Movvy',
    title: TITLE,
    description: DESCRIPTION,
    // The OG image itself comes from app/opengraph-image.tsx via Next's
    // file-based metadata convention — we don't repeat the file URL here.
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    // Same — twitter card image is generated by app/twitter-image.tsx.
  },
  // Favicon + Apple touch icon are auto-registered from app/icon.svg and
  // app/apple-icon.tsx — no metadata.icons block needed.
  robots: {
    index: true,
    follow: true,
  },
};

// Brand charcoal drives the browser UI (address bar on mobile, PWA chrome).
export const viewport: Viewport = {
  themeColor: '#282B2A',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-CA" className={archivoBlack.variable}>
      <body className="flex min-h-screen flex-col">
        <Splash />
        <Nav />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
