-- =============================================================================
-- Movvy — Migration 0016: Partner invite codes + invite list
--
-- WHY:
--   Companies and two-man crews are onboarded by their OWNER. The owner then
--   needs a way to bring additional drivers / movers into the team without
--   exposing the partner-onboarding flow to the open internet (otherwise
--   anyone could claim to be a Movvy driver). So:
--
--     1. Every partner_team and every company gets a unique 6-char invite
--        code (auto-generated by a BEFORE-INSERT trigger).
--     2. When the owner submits onboarding, they list each crew member's
--        email/phone in `partner_invites`. An edge function dispatches an
--        SMS (preferred) or email with the code + sign-up link.
--     3. New drivers/movers go to the "Join with code" screen, enter the
--        code + their email/phone. The accept edge function only lets them
--        in if their contact matches a pending invite for that team.
--
-- The code itself is not a secret — it's the (code, contact) pair that
-- authorises onboarding. Standard pattern (Slack workspace, Notion
-- teamspace, GitHub org invite).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. invite_code columns on partner_teams + companies
-- -----------------------------------------------------------------------------

alter table partner_teams
  add column invite_code text;
alter table companies
  add column invite_code text;

-- Unambiguous alphabet: no 0/O/1/I/L. 6 chars over 30 symbols = ~729M codes.
create or replace function gen_movvy_invite_code(p_prefix text)
returns text language plpgsql as $$
declare
  alphabet text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  code text;
  result text;
  attempts int := 0;
begin
  loop
    code := '';
    for i in 1..6 loop
      code := code || substr(alphabet, floor(random() * length(alphabet))::int + 1, 1);
    end loop;
    result := p_prefix || '-' || code;

    -- Uniqueness across BOTH tables — a code lives in one global namespace
    if not exists (select 1 from partner_teams where invite_code = result)
       and not exists (select 1 from companies where invite_code = result) then
      return result;
    end if;
    attempts := attempts + 1;
    if attempts > 12 then
      raise exception 'Could not generate unique invite code after % attempts', attempts;
    end if;
  end loop;
end;
$$;

-- Trigger: auto-fill invite_code when a partner_team or company is inserted
create or replace function set_partner_invite_code() returns trigger language plpgsql as $$
begin
  if new.invite_code is null then
    new.invite_code := gen_movvy_invite_code(
      case TG_TABLE_NAME when 'partner_teams' then 'TM' else 'CO' end
    );
  end if;
  return new;
end $$;

create trigger partner_teams_invite_code
  before insert on partner_teams
  for each row execute function set_partner_invite_code();

create trigger companies_invite_code
  before insert on companies
  for each row execute function set_partner_invite_code();

-- Backfill any pre-existing rows
update partner_teams
  set invite_code = gen_movvy_invite_code('TM')
  where invite_code is null;
update companies
  set invite_code = gen_movvy_invite_code('CO')
  where invite_code is null;

-- Lock down: codes are required after backfill, and globally unique
alter table partner_teams
  alter column invite_code set not null,
  add constraint partner_teams_invite_code_unique unique (invite_code);
alter table companies
  alter column invite_code set not null,
  add constraint companies_invite_code_unique unique (invite_code);

-- -----------------------------------------------------------------------------
-- 2. partner_invites — pending crew invitations
-- -----------------------------------------------------------------------------

create type partner_invite_status as enum ('pending', 'sent', 'accepted', 'expired', 'cancelled');

create table partner_invites (
  id uuid primary key default gen_random_uuid(),
  -- EXACTLY one of these is set (constraint below)
  team_id uuid references partner_teams(id) on delete cascade,
  company_id uuid references companies(id) on delete cascade,

  -- Role the invitee will fill
  role text not null check (role in ('driver', 'mover', 'dispatcher')),
  -- Display info pre-filled by the inviter
  full_name text,
  email citext,
  phone text,

  status partner_invite_status not null default 'pending',
  invited_by_profile_id uuid not null references profiles(id) on delete cascade,
  accepted_by_profile_id uuid references profiles(id) on delete set null,

  -- Lifecycle timestamps
  expires_at timestamptz not null default (now() + interval '14 days'),
  sent_at timestamptz,
  accepted_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),

  -- Send log (set by partners-invite-send) — channel + provider IDs for audit
  last_channel text check (last_channel in ('sms', 'email', 'both', null)),
  last_provider_msg_id text,
  last_send_error text,

  constraint partner_invites_one_recipient check (
    (team_id is not null)::int + (company_id is not null)::int = 1
  ),
  constraint partner_invites_has_contact check (
    email is not null or phone is not null
  ),
  constraint partner_invites_phone_format check (
    phone is null or phone ~ '^\+[1-9][0-9]{6,14}$'
  )
);

create index partner_invites_team_idx on partner_invites (team_id) where team_id is not null;
create index partner_invites_company_idx on partner_invites (company_id) where company_id is not null;
create index partner_invites_email_idx on partner_invites (lower(email)) where email is not null;
create index partner_invites_phone_idx on partner_invites (phone) where phone is not null;
create index partner_invites_status_idx on partner_invites (status);
create index partner_invites_invited_by_idx on partner_invites (invited_by_profile_id);

-- Auto-bump `updated_at` style triggers don't exist on this table — invites
-- are short-lived state machines so we just track the discrete timestamps.

-- -----------------------------------------------------------------------------
-- 3. RLS — invites are visible to the inviter, team owners, and the invitee
-- -----------------------------------------------------------------------------

alter table partner_invites enable row level security;

-- The inviter and any team/company member of the recipient team can read.
create policy partner_invites_read on partner_invites for select
  using (
    invited_by_profile_id = auth.uid()
    or (
      team_id is not null
      and exists (
        select 1 from partner_team_members ptm
        where ptm.team_id = partner_invites.team_id
          and ptm.profile_id = auth.uid()
          and ptm.removed_at is null
      )
    )
    or (
      company_id is not null
      and exists (
        select 1 from company_members cm
        where cm.company_id = partner_invites.company_id
          and cm.profile_id = auth.uid()
          and cm.removed_at is null
      )
    )
  );

-- No client INSERT/UPDATE/DELETE — all mutations go through edge functions
-- (partners-invite-send creates rows; partners-invite-accept updates them).
revoke insert, update, delete on partner_invites from authenticated, anon;
grant select on partner_invites to authenticated;

-- -----------------------------------------------------------------------------
-- 4. Helper RPC — look up a single invite for a given (code, contact) pair
-- -----------------------------------------------------------------------------
-- Used by partners-invite-accept. Returns null if no match.

create or replace function find_partner_invite(
  p_invite_code text,
  p_email text default null,
  p_phone text default null
) returns table (
  invite_id uuid,
  team_id uuid,
  company_id uuid,
  role text,
  status partner_invite_status,
  expires_at timestamptz,
  matched_team_id uuid,
  matched_company_id uuid
) language plpgsql security definer as $$
declare
  v_team_id uuid;
  v_company_id uuid;
begin
  -- Resolve the invite_code to whichever side owns it
  select id into v_team_id from partner_teams where invite_code = p_invite_code;
  select id into v_company_id from companies where invite_code = p_invite_code;

  if v_team_id is null and v_company_id is null then
    return; -- code doesn't exist
  end if;

  return query
    select pi.id,
           pi.team_id,
           pi.company_id,
           pi.role,
           pi.status,
           pi.expires_at,
           v_team_id,
           v_company_id
    from partner_invites pi
    where
      ((v_team_id is not null and pi.team_id = v_team_id)
       or (v_company_id is not null and pi.company_id = v_company_id))
      and pi.status in ('pending', 'sent')
      and pi.expires_at > now()
      and (
        (p_email is not null and lower(pi.email) = lower(p_email))
        or (p_phone is not null and pi.phone = p_phone)
      )
    limit 1;
end;
$$;

revoke all on function find_partner_invite(text, text, text) from public;
grant execute on function find_partner_invite(text, text, text) to authenticated, anon;
